plugins {
  id 'java'
  id 'war'
}

group 'ru.monyamau'
version '1.0'

repositories {
  mavenCentral()
}

ext {
  junitVersion = '5.13.2'
  springVersion = '7.0.8'
  springDataVersion = '2026.0.0'
  lombokVersion = '1.18.46'
  mapstructVersion = '1.6.3'
}

sourceCompatibility = '21'
targetCompatibility = '21'

tasks.withType(JavaCompile).configureEach {
  options.encoding = 'UTF-8'
}

dependencies {
  implementation platform("org.springframework:spring-framework-bom:${springVersion}")
  implementation platform("org.springframework.data:spring-data-bom:${springDataVersion}")
  providedCompile "jakarta.servlet:jakarta.servlet-api:6.1.0"

  runtimeOnly "com.mysql:mysql-connector-j:9.7.0"
  runtimeOnly "io.lettuce:lettuce-core:7.6.0.RELEASE"
  runtimeOnly "org.hibernate.validator:hibernate-validator:9.1.3.Final"

  implementation "org.mapstruct:mapstruct:${mapstructVersion}"
  implementation "io.minio:minio:9.0.3"
  implementation "org.hibernate.orm:hibernate-core:7.4.4.Final"
  implementation "org.springframework:spring-webmvc"
  implementation "org.springframework.data:spring-data-jpa"
  implementation "org.springframework.data:spring-data-redis"
  implementation "com.fasterxml.jackson.core:jackson-databind:2.22.1"
  implementation "org.mindrot:jbcrypt:0.4"
  implementation "jakarta.validation:jakarta.validation-api:3.1.1"


  compileOnly "org.projectlombok:lombok:${lombokVersion}"
  annotationProcessor "org.projectlombok:lombok:${lombokVersion}"
  annotationProcessor "org.mapstruct:mapstruct-processor:${mapstructVersion}"

  testImplementation("org.junit.jupiter:junit-jupiter-api:${junitVersion}")
  testRuntimeOnly("org.junit.jupiter:junit-jupiter-engine:${junitVersion}")
}

test {
useJUnitPlatform()}