mysql.driver_class=com.mysql.cj.jdbc.Driver
mysql.url=jdbc:mysql://localhost:3306/file_storage

minio.endpoint=http://localhost:9000
minio.bucket-name=user-files

redis.host=localhost
redis.port=6379

