mysql.url=jdbc:mysql://localhost:3306/${DB_NAME}
mysql.username=${DB_USER}
mysql.password=${DB_PASSWORD}

minio.bucket-name=${MINIO_BUCKET}
minio.access_key=${MINIO_USER}
minio.secret_key=${MINIO_PASSWORD}